# Generated by Django 3.1.4 on 2021-02-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_remove_user_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=None, verbose_name='Registered on'),
            preserve_default=False,
        ),
    ]
