# Generated by Django 3.1.4 on 2021-02-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_auto_20210207_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(null=True, verbose_name='Registered on'),
        ),
    ]
