# Generated by Django 3.1.4 on 2021-02-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0006_auto_20210207_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('', 'Male'), ('', 'Female')], default='male', max_length=10, verbose_name='gender'),
        ),
    ]
